### ISSUE TITLE
open source code for speed testing

### ISSUE THREAD

**Issue by gk966988** [loki-lab/english_ocr_serving#1]
Triton's inference speed is four times faster than Python. Can we open source code for speed testing?

**Comment by loki-lab** [comment]
yes, we can use docker to open source code and debug triton inference server

**Comment by loki-lab** [comment]
> Triton's inference speed is four times faster than Python. Can we open source code for speed testing?
yes, we can use docker to open source code and debug triton inference server

**Comment by loki-lab** [comment]
> Triton's inference speed is four times faster than Python. Can we open source code for speed testing?

yes, we can use docker to open source code and debug triton inference server

**Comment by gk966988** [comment]
> > Triton's inference speed is four times faster than Python. Can we open source code for speed testing?
> 
> yes, we can use docker to open source code and debug triton inference server

Sorry! What I mean is, can you provide the code for how you tested the speed

**Comment by loki-lab** [comment]
> > > Triton's inference speed is four times faster than Python. Can we open source code for speed testing?
> > 
> > 
> > yes, we can use docker to open source code and debug triton inference server
> 
> Sorry! What I mean is, can you provide the code for how you tested the speed

I used the Python time module to test the speed between Triton inference server and restAPI(flask)
